### ISSUE TITLE
Is creating a RNAStructViz C API a useful time investment?

### ISSUE THREAD

**Issue by maxieds** [gtDMMB/RNAStructViz#22]
We could expose a certain amount of our non-GUI functionality, like saving and plotting an arc diagram, etc., as a C-style API for coders who want to re-use our specific nice looking implementation of the core functionality ``RNAStructViz`` provides. I don't have a specific mock up of any solid working plans for this yet, but @annakirkpatrick and @ceheitsch, do you all think this is a worthy investment in a few hours of my RA time to make this small-sized API for StructViz come to life? 

It seems (to me) like a shame to have coded up such a good looking arc diagram implementation with Cairo, and then "selfishly" not let other programs and API work get ahold of it to build on the solid work we have already done here. And at least this way, we get more control over standardizing what parts of ``RNAStructViz`` we expose to external code. 

Let me know any thoughts on this idea.

**Comment by annakirkpatrick** [comment]
@maxieds @ceheitsch I have looked at available arc diagram-style visualization software recently because of Justin's project. So I'm going to make note of some information/links that might be helpful in answering Maxie's question.

Vienna does not produce arc diagrams, but it does produce mountain diagrams (e.g. https://www.tbi.univie.ac.at/RNA/gfx/5smnt.png), along with the radial diagrams that biologists like.

The R package R4RNA is an open source package for doing lots of RNA computation and visualization with RNA in R. It draws some very nice linear arc diagrams and this function forms the backend of R-chie (which I think @maxieds has looked into for the application note).

**Comment by maxieds** [comment]
Closing this inactive discussion for now.
