### ISSUE TITLE
New file window suddenly blank

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#68]
Functionality was added to the file window.  However, after playing around with the program for a while (i.e. no idea what was done that might have caused this problem) the new part of the window is blank.  See attached.
![Screen Shot 2019-12-04 at 2 43 52 PM](https://user-images.githubusercontent.com/43553267/70175506-d90a4d00-16a4-11ea-9d2d-60b3f75a99c3.png)

**Comment by maxieds** [comment]
@ceheitsch 
This should be fixed in the newesr release, **v2.0.6-testing**. You will need to upgrade. 

The problem was that calling ``Fl_File_Chooser->add_extra(...)`` twice on the same object leads to undefined behavior in FLTK. Now we delete the file chooser each time we renew its configuration settings. I checked it for solution on Mac and Linux.

**Comment by ceheitsch** [comment]
Unable to reproduce, so closing for now.
