### ISSUE TITLE
add button to select "use default folder names"

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#73]
It seems that the default folder names are now used automatically when using "Select All Files".  This should be an option (which could be selected by default, like the "Avoid loading..." one) since it won't always be the desired behavior.

The option does appear when just a subset of files are chosen manually in the "New Folder Added" window.

**Comment by maxieds** [comment]
@ceheitsch 

In general, if the option to enable so-called "sticky folder names" is enabled in the config options (see where to re-enable/disable this feature below), then if there is a saved folder name, the UI will skip asking the user for a new folder name when loading files. This is intentionally meant to be a time saver for users:

![Screenshot at 2019-12-13 13-41-45](https://user-images.githubusercontent.com/22165688/70823741-a51ede00-1dae-11ea-9fa3-c70974792488.png)

You are correct in that, prior to the bug fix I'm about to add to the code, if there is a stick folder name already saved for that sequence, it always uses the pre-defined folder name -- even if the option to use sticky folder names is disabled. This part of things is a bug that will be fixed by the time I get around to releasing **v2.2.1-testing** later today.

**Comment by ceheitsch** [comment]
To be clear, I wasn't worried about remembering the folder names, but rather that when loading a lot of files, the program wasn't querying which folder name should be used.  Perhaps because the sticky folder options was selected?

**Comment by maxieds** [comment]
@ceheitsch 
Most likely, yes. If that checkbox is selected, and there is already a saved "sticky" folder name on record for the sequence, then when loading files with that base sequence RNAStructViz should skip prompting the user for a new folder name. This is an intentional convenience for users who load many of the same files in the application over and over again.

**Comment by maxieds** [comment]
Mac OSX 10.14.x support verified!
