### ISSUE TITLE
sample 5S_S.cerevisiae_UNAfold.ct has two structures in it

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#76]
File length should be 119, not 238.

**Comment by maxieds** [comment]
@ceheitsch 

It turns out that the structures in the original ``5S_S.cerevisiae_UNAfold.ct`` were not duplicates. I interpreted this to mean that they were both CT file samples generated by ``UNAfold`` at some point. For the record, the stochastic sampling utility bundled with ``RNAstructure`` outputs a CT file full of concatenated samples in CT format, one right after the other, so I assume the second structure in our file was generated according to a similar scheme in the former program. 

To preserve both samples historically bundled with our RNAStructViz distribution, I kept the first structure in [``5S_S.cerevisiae_UNAfold.ct``](https://github.com/gtDMMB/RNAStructViz/blob/master/sample-structures/5S_S.cerevisiae_UNAfold.ct) and moved the second structure to a new file (also bundled) named [``5S_S.cerevisiae_UNAfold_structure2.ct``](https://github.com/gtDMMB/RNAStructViz/blob/master/sample-structures/5S_S.cerevisiae_UNAfold_structure2.ct). In principle, given this convention in a number of sample generation applications, we might want to consider allowing CT/NOPCT files contain multiple samples. The current code ignores all but the first in a file.

This fix should be visible in the new **v2.2.1-testing** release that will be available via ``brew`` for Mac OS later today.

**Comment by maxieds** [comment]
@ceheitsch 
Please make sure to delete the existing sequences folder in your home directory:
```bash
$ rm -rf ~/RNAStructViz
```
Then copy the structures again using the help (question mark) button at the upper right of the LHS main window pane: 

![Screenshot at 2019-12-13 15-55-36](https://user-images.githubusercontent.com/22165688/70831657-21bab800-1dc1-11ea-9d9a-5c974b9b7f33.png)

**Comment by ceheitsch** [comment]
All sorted.  Opening a feature request for loading multiple structures in a single ct file makes sense.  The number should be capped as with the current dot-bracket ones.
