### ISSUE TITLE
cannot install on macOS

### ISSUE THREAD

**Issue by spoznan** [gtDMMB/RNAStructViz#81]
Hi,

Can you please help me install this on my macOS 10.14.6?  When I try

$ brew install gtDMMB/core/RNAStructViz

I get 

==> Tapping gtdmmb/core
Cloning into '/usr/local/Homebrew/Library/Taps/gtdmmb/homebrew-core'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 33 (delta 1), reused 18 (delta 1), pack-reused 0
Unpacking objects: 100% (33/33), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/gtdmmb/homebrew-core/Formula/rnastructvizdev.rb
rnastructvizdev: cannot load such file -- /usr/local/Homebrew/Library/Taps/gtdmmb/homebrew-core/LocalUtils/github_gatech.rb
Error: Cannot tap gtdmmb/core: invalid syntax in tap!

Svetlana

**Comment by maxieds** [comment]
@spoznan 
Svetlana, 

It's weird that the problem is the ``rnastructvizdev.rb`` formula, which to be honest I have never tested. Nonetheless, I deleted it. Please try again by running the following commands:
```bash
$ brew update
$ brew install gtdmmb/core/rnastructviz
```
Keep in mind that if you've never installed this application before, the dependencies (Vienna, FLTK) could take 10-15 minutes to build depending on the speed of your system.

**Comment by spoznan** [comment]
That worked. Thanks.
