### ISSUE TITLE
file list in structure/right-hand-side window doesn't update 

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#95]
The nopct file (CP000493_ad.nopct) was first loaded.  Then the diagram button was clicked.  Afterwards, the load files menu was reopened and the rest of the dot files for this sequence were loaded.  Eight more files were added which shows up in the left-hand-side window count (which shows +9 in the image) but the right-hand-side (RHS) window does not update automatically.  There is still only the nopct file listed on the RHS.  A manual "refresh" would be fine in this situation, but there doesn't seem to be a way to do that.  Note that (1) clicking on the sequence button in the LHS window does not work.  Also (2) the open diagram window does automatically update with additional structure files
<img width="646" alt="Screen Shot 2020-05-26 at 11 08 55 AM" src="https://user-images.githubusercontent.com/43553267/82918554-e5c87900-9f42-11ea-837d-f1406906f0df.png">

**Comment by maxieds** [comment]
@ceheitsch 
Ok. My bad on not testing this enough before. 

I am using the stock sample structures to verify the fix for *C. elegans*. After loading just one structure for this organism:

![Screen Shot 2020-05-28 at 1 21 01 AM](https://user-images.githubusercontent.com/22165688/83102063-b1a7a200-a081-11ea-84e5-ccaded108c81.png)

Now after clicking on the *Load Files* button again, and loading everything in the directory:

![Screen Shot 2020-05-28 at 1 21 13 AM](https://user-images.githubusercontent.com/22165688/83102109-c3894500-a081-11ea-9677-7b286b5fbba1.png)

Note that I tested this with another *C. cerevisiae* by deleting some of the loaded structures and then reloading all of them. The result is that after reloading, the RHS window pane is repopulated with all possible structures. Great, now as expected!

This fix will go under the release tagged **v2.3.8-testing**. I will release that as a brew formula after a couple of fixes for other issues get added as well.

**Comment by ceheitsch** [comment]
Working as expected now; thanks!
