### ISSUE TITLE
minor formatting problem in "Table" tab of Statistics window

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#96]
The last four columns of in the Table tab of the Statistics window are the counts of the G-C, A-U, G-U, and other (noncanonical) base pairs in each structure.  

These numbers are available in the Base Pairings tab:
<img width="1181" alt="Screen Shot 2020-06-02 at 12 09 10 PM" src="https://user-images.githubusercontent.com/43553267/83543394-5125c400-a4ca-11ea-8010-ee2d2ab0d1be.png">

In this case, the first line (for AP00618_az.nopct) is offset to the left, presumable because the file name is so much shorter than the others: 
<img width="1208" alt="Screen Shot 2020-06-02 at 12 09 46 PM" src="https://user-images.githubusercontent.com/43553267/83543757-e4f79000-a4ca-11ea-8e7f-2af1225a94bd.png">

Sequence files are in table.tar.gz 
[table.tar.gz](https://github.com/gtDMMB/RNAStructViz/files/4718390/table.tar.gz)

**Comment by maxieds** [comment]
@ceheitsch 
Can you please post the sequence file so I can test? I suspect this is easy to fix. I have also caught a few other formatting related snags in the Stats window table tab.

**Comment by maxieds** [comment]
@ceheitsch 
The fix for this minor formatting issue is found in the latest release (version **v2.3.8-testing**). Please observe the fixes below, and then upgrade using ``brew`` as usual:

![Screen Shot 2020-06-16 at 3 30 48 AM](https://user-images.githubusercontent.com/22165688/84744973-ecff0780-af81-11ea-8dfd-e8e5484989d1.png)

![Screen Shot 2020-06-16 at 3 30 57 AM](https://user-images.githubusercontent.com/22165688/84744974-ecff0780-af81-11ea-884d-cf4f811c307a.png)

**Comment by ceheitsch** [comment]
Tabbing problem sorted in new images.
