### ISSUE TITLE
button next to xml button

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/RNAStructViz#98]
There's an icon/button next to the xml one (from the previous issue).  It's not clear what it does, and doesn't seem to be active anyway.  Again, better to remove at this point.  If you want list these in issues as possible feature upgrades, that's fine.

**Comment by maxieds** [comment]
@ceheitsch 
There are tooltips on almost all of the widget buttons in the StructViz GUI. What this second icon does (you can click on them as well) is specify whether or not the currently loaded file should be auto re-loaded the next time the application starts -- effectively pinning that structure file to the user's workspace until it is deselected. This is actually a desirable feature since restarting the application, or picking out a preset list of structures to load can be troublesome if they are in different directories, or if the CT/NOPCT files come from a large folder of data that is hard to navigate:

**(Tooltip documenting the "hidden" feature)**

![tooltip](https://user-images.githubusercontent.com/22165688/89065696-288b4080-d33a-11ea-8c0d-dc7c7aa1195f.png)

**(Demo of re-loading the structures at next launch)**

![reloading-autoloaded-struct-files](https://user-images.githubusercontent.com/22165688/89065694-288b4080-d33a-11ea-95c6-1ca4adfb7f8d.png)

Note that taking these screenshots did bring up an unanticipated bug in that the last release will only load one file per base sequence at a time. This will be fixed when I issue a new release, most likely by the end of today.

**Comment by maxieds** [comment]
@ceheitsch 
There is also [documentation for this button](https://github.com/gtDMMB/RNAStructViz/wiki/FAQ#i-always-use-rnastructviz-to-visualize-sequences-x-y-and-z-is-there-a-way-to-automatically-load-my-most-used-structures-for-these-sequences-every-time-the-application-starts) indexed within the WIKI FAQ page.
